# **Appending, Concatenating, Merging, and Joining**

There are 4 main ways of combining DataFrames together: Appending, Concatenating, Joining and Merging. In this lecture we will discuss these 4 methods with examples.

---



**Append** is the specific case(axis=0, join='outer') of concat


**Concat** gives the flexibility to join based on the axis( all rows or all columns)

**Join** is based on the indexes (set by set_index)/key columns on how variable =['left','right','inner','outer']

**Merge** is based on any particular column each of the two dataframes, this columns are variables on like 'left_on', 'right_on', 'on'

**Example DataFrames**

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']}
                    )

In [ ]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']}
                    )

In [ ]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']}
                   )

In [ ]:
df4 = pd.DataFrame({'C': ['C12', 'C13', 'C14', 'C15'],
                    'A': ['A12', 'A13', 'A14', 'A15'],
                    'D': ['D12', 'D13', 'D14', 'D15'],
                    'B': ['B12', 'B13', 'B14', 'B15']}
                    )

In [ ]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df2

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [ ]:
df3

     A    B    C    D
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [ ]:
df4

     C    A    D    B
0  C12  A12  D12  B12
1  C13  A13  D13  B13
2  C14  A14  D14  B14
3  C15  A15  D15  B15

**Appending**

The most basic way of combining method for DataFrames.

In [ ]:
df1.append(df3)

     A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [ ]:
df1.append(df3, ignore_index=True)  #new indexes

     A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
4   A8   B8   C8   D8
5   A9   B9   C9   D9
6  A10  B10  C10  D10
7  A11  B11  C11  D11

**Concatenation**

Concatenation basically glues together multi DataFrames. Keep in mind that dimensions should match along the axis you are concatenating on. You can use pd.concat and pass in a list of DataFrames to concatenate together:

In [ ]:
# Default = rows onto rows

pd.concat([df1,df2,df3])    #baştakine göre sutünları sıralıyor.

     A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A4   B4   C4   D4
1   A5   B5   C5   D5
2   A6   B6   C6   D6
3   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [ ]:
pd.concat([df1.iloc[:,:2],df2.iloc[:,1:],df3],ignore_index=True)

      A    B    C    D
0    A0   B0  NaN  NaN
1    A1   B1  NaN  NaN
2    A2   B2  NaN  NaN
3    A3   B3  NaN  NaN
4   NaN   B4   C4   D4
5   NaN   B5   C5   D5
6   NaN   B6   C6   D6
7   NaN   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
pd.concat([df1.iloc[:,:2], df2.iloc[:,1:], df3])

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
0  NaN   B4   C4   D4
1  NaN   B5   C5   D5
2  NaN   B6   C6   D6
3  NaN   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [ ]:
pd.concat([df1,df2,df3], axis=1)

    A   B   C   D   A   B   C   D    A    B    C    D
0  A0  B0  C0  D0  A4  B4  C4  D4   A8   B8   C8   D8
1  A1  B1  C1  D1  A5  B5  C5  D5   A9   B9   C9   D9
2  A2  B2  C2  D2  A6  B6  C6  D6  A10  B10  C10  D10
3  A3  B3  C3  D3  A7  B7  C7  D7  A11  B11  C11  D11

In [ ]:
pd.concat([df1.iloc[:2],df2.iloc[1:],df3], axis=1)

     A    B    C    D    A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN   A8   B8   C8   D8
1   A1   B1   C1   D1   A5   B5   C5   D5   A9   B9   C9   D9
2  NaN  NaN  NaN  NaN   A6   B6   C6   D6  A10  B10  C10  D10
3  NaN  NaN  NaN  NaN   A7   B7   C7   D7  A11  B11  C11  D11

**Different Indexes**

In [ ]:
df4 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                    index=[0,1,2,3])

df5 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                    index=[4,5,6,7]) 

df6 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
                    index=[8,9,10,11])

In [ ]:
df4

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df5

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
df6

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
pd.concat([df4,df5,df6], axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [ ]:
pd.concat([df4,df5,df6], axis=1,ignore_index=True)   #not logical

     0    1    2    3    4    5    6    7    8    9    10   11
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [ ]:
pd.concat([df4,df5.reset_index(drop=True),df6.reset_index(drop=True)], axis=1,ignore_index=True)

   0   1   2   3   4   5   6   7    8    9    10   11
0  A0  B0  C0  D0  A4  B4  C4  D4   A8   B8   C8   D8
1  A1  B1  C1  D1  A5  B5  C5  D5   A9   B9   C9   D9
2  A2  B2  C2  D2  A6  B6  C6  D6  A10  B10  C10  D10
3  A3  B3  C3  D3  A7  B7  C7  D7  A11  B11  C11  D11

In [ ]:
pd.concat([df4,df5,df6], axis=0)  # bestie

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

**Merging**

The merge function allows you to merge DataFrames together using a similar logic as merging SQL Tables together.Merge enough for all combinings.

In [ ]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                      'C': ['C0', 'C1', 'C2', 'C3'],
                      'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [ ]:
right

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [ ]:
pd.merge(left, right, how = 'inner', on = 'key')  
#on=key uses same keys.Inner intercepts them.
#yanyana birleştirir.axis olayı yok.

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [ ]:
left2 = pd.DataFrame({'key': ['K0', 'K1', 'K4', 'K5'],   #keys are different
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right2 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                       'C': ['C0', 'C1', 'C2', 'C3'],
                       'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
left2

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K4  A2  B2
3  K5  A3  B3

In [ ]:
right2

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [ ]:
pd.merge(left2, right2, how = 'inner', on = 'key') # on=key uses same keys.Inner intercepts them.

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1

In [ ]:
pd.merge(left2, right2, how = 'outer', on = 'key')  # bileşim,all of them

  key    A    B    C    D
0  K0   A0   B0   C0   D0
1  K1   A1   B1   C1   D1
2  K4   A2   B2  NaN  NaN
3  K5   A3   B3  NaN  NaN
4  K2  NaN  NaN   C2   D2
5  K3  NaN  NaN   C3   D3

In [ ]:
pd.merge(left2, right2, how = 'left', on = 'key')  #Lefti öncelikli aldı.leftlerin keylerinin tümünü aldı.rightın kesişenlerini ekledi.

  key   A   B    C    D
0  K0  A0  B0   C0   D0
1  K1  A1  B1   C1   D1
2  K4  A2  B2  NaN  NaN
3  K5  A3  B3  NaN  NaN

In [ ]:
pd.merge(left2, right2, how = 'right', on = 'key')

  key    A    B   C   D
0  K0   A0   B0  C0  D0
1  K1   A1   B1  C1  D1
2  K2  NaN  NaN  C2  D2
3  K3  NaN  NaN  C3  D3

In [ ]:
left3 = pd.DataFrame({'key': ['K0', 'K0', 'K1', 'K1']    # repeated keys are available 
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right3 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K2'],
                       'C': ['C0', 'C1', 'C2', 'C3'],
                       'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
left3

  key   A   B
0  K0  A0  B0
1  K0  A1  B1
2  K1  A2  B2
3  K1  A3  B3

In [ ]:
right3

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K2  C3  D3

In [ ]:
pd.merge(left3, right3, how = 'inner', on = 'key')  #ortak keyleri almış,kesiştirmiş

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K0  A1  B1  C0  D0
2  K1  A2  B2  C1  D1
3  K1  A3  B3  C1  D1

In [49]:
pd.merge(left3, right3, how = 'outer', on = 'key')

  key    A    B   C   D
0  K0   A0   B0  C0  D0
1  K0   A1   B1  C0  D0
2  K1   A2   B2  C1  D1
3  K1   A3   B3  C1  D1
4  K2  NaN  NaN  C2  D2
5  K2  NaN  NaN  C3  D3

In [50]:
pd.merge(left3, right3, how = 'left', on = 'key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K0  A1  B1  C0  D0
2  K1  A2  B2  C1  D1
3  K1  A3  B3  C1  D1

In [52]:
pd.merge(left3, right3, how = 'right', on = 'key')

  key    A    B   C   D
0  K0   A0   B0  C0  D0
1  K0   A1   B1  C0  D0
2  K1   A2   B2  C1  D1
3  K1   A3   B3  C1  D1
4  K2  NaN  NaN  C2  D2
5  K2  NaN  NaN  C3  D3

In [53]:
left4 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right4 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                       'key2': ['K0', 'K0', 'K0', 'K0'],
                       'C': ['C0', 'C1', 'C2', 'C3'],
                       'D': ['D0', 'D1', 'D2', 'D3']})

In [54]:
left4

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [55]:
right4

  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [56]:
pd.merge(left4,right4,how="inner",on=["key1","key2"])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [57]:
pd.merge(left4,right4,how="outer",on=["key1","key2"])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

In [58]:
pd.merge(left4,right4,how="left",on=["key1","key2"])

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [59]:
pd.merge(left4,right4,how="right",on=["key1","key2"])

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [60]:
left5 = pd.DataFrame({'lkey': ['x', 'y', 'z', 'x', 'z'],
                     'lvalue': [2, 3, 5, 7, 0]})
right5 = pd.DataFrame({'rkey': ['a', 'x', 'z', 'b'],
                     'rvalue': [7, 8, 9, 10]})

In [61]:
left5

  lkey  lvalue
0    x       2
1    y       3
2    z       5
3    x       7
4    z       0

In [62]:
right5

  rkey  rvalue
0    a       7
1    x       8
2    z       9
3    b      10

In [63]:
pd.merge(left5, right5, left_on = "lkey", right_on="rkey", how = "inner") #çakışanları aldı

  lkey  lvalue rkey  rvalue
0    x       2    x       8
1    x       7    x       8
2    z       5    z       9
3    z       0    z       9

In [64]:
pd.merge(left5, right5, left_on = "lkey", right_on="rkey", how = "outer")

  lkey  lvalue rkey  rvalue
0    x     2.0    x     8.0
1    x     7.0    x     8.0
2    y     3.0  NaN     NaN
3    z     5.0    z     9.0
4    z     0.0    z     9.0
5  NaN     NaN    a     7.0
6  NaN     NaN    b    10.0

In [65]:
pd.merge(left5, right5, left_on = "lkey", right_on="rkey", how = "left")

  lkey  lvalue rkey  rvalue
0    x       2    x     8.0
1    y       3  NaN     NaN
2    z       5    z     9.0
3    x       7    x     8.0
4    z       0    z     9.0

In [66]:
pd.merge(left5, right5, left_on = "lkey", right_on="rkey", how = "right")

  lkey  lvalue rkey  rvalue
0  NaN     NaN    a       7
1    x     2.0    x       8
2    x     7.0    x       8
3    z     5.0    z       9
4    z     0.0    z       9
5  NaN     NaN    b      10

In [67]:
left6 = pd.DataFrame({'lkey': ['x', 'y', 'z', 'x'],
                        'lvalue': [2, 3, 5, 7]})
right6 = pd.DataFrame({'rkey': ['a', 'b', 'c', 'b'],
                         'rvalue': [7, 8, 9, 10]})

In [70]:
left6

  lkey  lvalue
0    x       2
1    y       3
2    z       5
3    x       7

In [69]:
right6

  rkey  rvalue
0    a       7
1    b       8
2    c       9
3    b      10

In [72]:
pd.merge(left6, right6, left_on = "lkey", right_on="rkey",how="inner")

Empty DataFrame
Columns: [lkey, lvalue, rkey, rvalue]
Index: []

In [73]:
pd.merge(left6, right6,  left_on = "lkey", right_on="rkey", how = "outer")

  lkey  lvalue rkey  rvalue
0    x     2.0  NaN     NaN
1    x     7.0  NaN     NaN
2    y     3.0  NaN     NaN
3    z     5.0  NaN     NaN
4  NaN     NaN    a     7.0
5  NaN     NaN    b     8.0
6  NaN     NaN    b    10.0
7  NaN     NaN    c     9.0

In [74]:
pd.merge(left6, right6, left_on = "lkey", right_on="rkey", how = "left")

  lkey  lvalue rkey  rvalue
0    x       2  NaN     NaN
1    y       3  NaN     NaN
2    z       5  NaN     NaN
3    x       7  NaN     NaN

In [75]:
pd.merge(left6, right6, left_on = "lkey", right_on="rkey", how = "right")

  lkey  lvalue rkey  rvalue
0  NaN     NaN    a       7
1  NaN     NaN    b       8
2  NaN     NaN    c       9
3  NaN     NaN    b      10

In [76]:
pd.merge(left6, right6, left_index=True, right_index=True)  #indexlere birleştirme yapar.indexe göre concatla aynı olmuş oldu.

  lkey  lvalue rkey  rvalue
0    x       2    a       7
1    y       3    b       8
2    z       5    c       9
3    x       7    b      10

**Joining**

Joining is a convenient method for combining the columns of two potentially differently-indexed DataFrames into a single result DataFrame.

In [77]:
left7 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index = ['K0', 'K1', 'K2']) 

right7 = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index = ['K0', 'K2', 'K3'])

In [78]:
left7

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [79]:
right7

     C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [84]:
left7.join(right7)   #defaultu left.sadece indexler üzerinden işlem yapar.

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [80]:
left7.join(right7, how = 'left')  #default left üstteki satır ile aynı.

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [81]:
left7.join(right7, how = 'outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

In [82]:
left7.join(right7, how = "inner")

     A   B   C   D
K0  A0  B0  C0  D0
K2  A2  B2  C2  D2

In [83]:
left7.join(right7, how = "right")

      A    B   C   D
K0   A0   B0  C0  D0
K2   A2   B2  C2  D2
K3  NaN  NaN  C3  D3

In [86]:
left8 = pd.DataFrame({'key': ['K0', 'K2', 'K3', 'K4', 'K5', 'K6'],    #uzunlukları farklı
                   'X': ['X0', 'X2', 'X3', 'X4', 'X5', 'X6']})

right8 = pd.DataFrame({'key': ['K0', 'K2', 'K3'],
                      'Y': ['Y0', 'Y2', 'Y3']})

In [87]:
left8

  key   X
0  K0  X0
1  K2  X2
2  K3  X3
3  K4  X4
4  K5  X5
5  K6  X6

In [88]:
right8

  key   Y
0  K0  Y0
1  K2  Y2
2  K3  Y3

In [89]:
#left8.join(right8)  # gives an error (columns overlap but no suffix specified: Index(['key'], dtype='object'))
#aynı isimde column kabul etmez.

In [90]:
left8.join(right8, lsuffix='_left', rsuffix='_right')   #eğer aynı column varsa lefttekinin başına left ,righttakinin  başına right yaz.

  key_left   X key_right    Y
0       K0  X0        K0   Y0
1       K2  X2        K2   Y2
2       K3  X3        K3   Y3
3       K4  X4       NaN  NaN
4       K5  X5       NaN  NaN
5       K6  X6       NaN  NaN

In [92]:
left8.set_index("key").join(right8, lsuffix='_left', rsuffix='_right')

      X  key    Y
key
K0   X0  NaN  NaN
K2   X2  NaN  NaN
K3   X3  NaN  NaN
K4   X4  NaN  NaN
K5   X5  NaN  NaN
K6   X6  NaN  NaN

In [ ]:
left8.join(right8,on="key") #ValueError: You are trying to merge on object and int64 columns. If you wish to proceed you should use pd.concat

In [94]:
left8

  key   X
0  K0  X0
1  K2  X2
2  K3  X3
3  K4  X4
4  K5  X5
5  K6  X6

In [95]:
right8

  key   Y
0  K0  Y0
1  K2  Y2
2  K3  Y3

In [96]:
left8.join(right8.set_index("key"),on="key")  #keyler sutünda kaldı

  key   X    Y
0  K0  X0   Y0
1  K2  X2   Y2
2  K3  X3   Y3
3  K4  X4  NaN
4  K5  X5  NaN
5  K6  X6  NaN